// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCthZSkNJfaCtVYL7uJkBZjvO2oDwm4eog',
    appId: '1:325962037535:web:d8df6a117eec848ac7d82a',
    messagingSenderId: '325962037535',
    projectId: 'fir-77d21',
    authDomain: 'fir-77d21.firebaseapp.com',
    storageBucket: 'fir-77d21.appspot.com',
    measurementId: 'G-65DRLHNB7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtGdG0i6aM8LTfjYqinDQ6d--kerCzGU',
    appId: '1:325962037535:android:9fb21893f5731f51c7d82a',
    messagingSenderId: '325962037535',
    projectId: 'fir-77d21',
    storageBucket: 'fir-77d21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5yeAklB8d9WPoBk3Q5j9c0Qn9vKWYi8w',
    appId: '1:325962037535:ios:1a038ad0effb9bb8c7d82a',
    messagingSenderId: '325962037535',
    projectId: 'fir-77d21',
    storageBucket: 'fir-77d21.appspot.com',
    iosBundleId: 'com.example.doan',
  );
}
